# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

target 'optAddict' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # Pods for optAddict
 pod 'Firebase/Core', '~> 5.3.0'
 pod 'Firebase/Auth', '~> 5.3.0'
 pod 'Firebase/Database', '~> 5.3.0'
 pod 'Firebase/Firestore’, '~> 5.3.0'

end
